name: Python Lint and Tests

# Run on all branches on push, and on pull requests
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run Pylint
        run: pylint app.py model.py tests/

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run tests
        run: pytest tests/


